services:
  db:
    env_file: .env
    image: postgres:18.0-alpine3.22
    container_name: tutorial_db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGPORT: ${DATABASE_PORT}
    ports:
      - "${DATABASE_HOST_FORWARD_PORT}:${DATABASE_PORT}"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
    driver: local
