# https://github.com/tox-dev/action-pre-commit-uv

name: "pre-commit"

on:
  push:
    branches:
      - main
  pull_request: ~

env:
  PYTHON_VERSION: 3.13.7
  UV_VERSION: 0.8.4
  PRE_COMMIT_VERSION: 4.2.0
  PRE_COMMIT_UV_VERSION: 4.1.4

jobs:
  run-pre-commit:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      name: Checkout

    - name: Install uv ${{ env.UV_VERSION }} & Python ${{ env.PYTHON_VERSION }}
      uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
      with:
        enable-cache: true
        python-version: ${{ env.PYTHON_VERSION }}
        version: ${{ env.UV_VERSION }}

    - name: pre-commit cache
      id: precommit_cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ runner.os }}-${{ env.PYTHON_VERSION }}-pre-commit-${{ env.PRE_COMMIT_VERSION }}-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: pre-commit-${{ runner.os }}-${{ env.PYTHON_VERSION }}-pre-commit-${{ env.PRE_COMMIT_VERSION }}-

    - name: Run pre-commit
      # TODO:
      #   Try to separate the installation of pre-commit and pre-commit-uv,
      #   without hurting the cache.
      # FIXME:
      #   https://github.com/tox-dev/pre-commit-uv/issues/70
      #   Try to add back the following line when the issue is fixed:
      #   --with pre-commit-uv==${{ env.PRE_COMMIT_UV_VERSION }}
      run: >
        uv run
        --no-sync
        --with pre-commit==${{ env.PRE_COMMIT_VERSION }}
        pre-commit run --all-files
